### ISSUE TITLE
better warning when running on an incompatible version

### ISSUE THREAD

**Issue by psifertex** [rikodot/binja_native_sigscan_loader#1]
Because this loader knows the version it's currently running on (and until the upstream feature exists that would prevent even the loader from being run on a version "too new", it would be great if the loader would alert the user when they're trying to run on a release that's too new and specify what version the plugin was built for. In this case, currently built for stable, 3.3.3996 which is a few API version changes behind the latest development 3.4 builds.

**Comment by rikodot** [comment]
Customized the script to allow for multiple binaries based on the API used. When user switches to different Binary Ninja version, script now automatically deletes old incompatible native plugin and installs a correct one according to the new Binary Ninja version - if provided by the plugin developer. More detailed explanation provided in [this commit](https://github.com/rikodot/binja_native_plugin_loader/commit/571ddbebdd11a0d16375db9bac052fbf02f9627c).
