### ISSUE TITLE
Current Version Unsupported (3.5.4526)

### ISSUE THREAD

**Issue by confusingowl** [rikodot/binja_native_sigscan_loader#2]
Thought I'd leave this here; as the title states the current version of binary ninja does not work with this plugin.

**Comment by rikodot** [comment]
Yes I am aware. I am very busy with other projects right now and no longer have the environment I used for compiling required binaries. Which platform are you on, Windows/Linux/MacOs? I might compile them in upcoming days.

**Comment by rikodot** [comment]
I have updated the plugin and made a few improvements. Now you may manually download it or wait until it is updated in the Vector35 community repository.
Thank you for your interest and sorry for the delay.
